# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 15 Pro Max"
])

languages([
  "en",
  "tr",
  "ru"
])

dark_mode(false)

scheme("GDEBankUITests")

output_directory("./screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

launch_arguments(["-UITests"])